CREATE TABLE Customers (
  ID AUTOINCREMENT PRIMARY KEY,
  FullName TEXT(255) NOT NULL,
  MobileNumber TEXT(25) NOT NULL,
  DOB DATETIME NOT NULL,
  CalculatedAge INTEGER NOT NULL,
  FinalDiscountPercent INTEGER NOT NULL DEFAULT 0,
  VisitDate DATETIME DEFAULT Now()
);
